# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Espai.create([
  { :nom => "Espai Mezzine", :descripcio => "Barcelona Digital posa a disposició d’entitats, empreses i institucions el seu Mezzanine, un espai versàtil ubicat al mateix Edifici Media-TIC pensat per allotjar reunions de treball, cursos de formació, conferències, actes d’empresa, exhibició de productes i qualsevol acte de caire corporatiu o públic.\r\n \r\nEl Mezzanine és un espai TIC amb tota classe d’equipaments de projecció, àudio, vídeo i telecomunicacions de darrera generació, adaptable a la mida de cada necessitat. Així mateix, el centre posa a la vostra disposició serveis de fotografia, hostesses, acreditacions, càtering i traducció simultània.", :direccio => "C. Roc Boronat 117", :codipostal => "08005", :lat => 41.401680440050626, :lang => 2.1958065032958984, :tags => "mobils, ios, android", :imatge => "http://www.bdigital.org/Documents/Mezzanine/Mezzanine-II_gran.jpg", :created_at => "2011-12-15 09:59:46", :updated_at => "2011-12-15 09:59:46" }
])


